apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: todo-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: todo-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_DATABASE
              value: "testdb"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_ROOT_PASSWORD
              value: "password"
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: todo-app
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: fastapi
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: your-fastapi-image:latest
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: kingtux187/fastapi-todo:v1
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: todo-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: fastapi
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  namespace: todo-app
spec:
  selector:
    matchLabels:
      app: angular
  replicas: 1
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
        - name: angular
          image: kingtux187/angular-todo:v1
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: angular
  namespace: todo-app
spec:
  ports:
    - port: 4200
      targetPort: 4200
  selector:
    app: angular
  type: LoadBalancer
