version: '3.8'
services:
  fastapi:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - DB_PORT=8181
      - DB_HOST=db
      - DB_USER=user
      - DB_PWD=password
      - DB_NAME=testdb
      - BACKEND_URL=http://localhost
      - BACKEND_PORT=4200
      - BACKEND_HOST=0.0.0.0
    ports:
      - "8000:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'testdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "8181:3306"
    volumes:
      - db_data:/var/lib/mysql

  angular:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"

volumes:
  db_data:
